<?php

/**
 * @file
 * The module file for snippet.
 * 
 */

/**
 * Menu item prefix.
 */
define('SNIPPETS_MENU_PREFIX', 'admin/structure');

/**
 * Menu item prefix.
 */
define('SNIPPETS_LIST_MENU', SNIPPETS_MENU_PREFIX . '/snippet-list');

/**
 * Menu item for updating the highlighted.
 */
define('SNIPPETS_UI_UPDATE_MENU', SNIPPETS_LIST_MENU . '/snippet-update');



/**
 * Implementation of hook_ctools_plugin_directory().
 * @param $module
 * @param $type
 */
function snippet_ctools_plugin_directory($module, $type) {
  // Load the plugins.
    return "plugins/{$type}";
}

/**
 * Implementation of hook_ctools_plugin_api().
 *
 * Tell CTools that we support the default_snippet_presets API.
 */
function snippet_ctools_plugin_api($owner, $api) {
  if ($owner == 'snippet' && $api == 'default_snippet') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_menu().
 */
function snippet_menu() {
  
  $items = array();
  
  $items[SNIPPETS_LIST_MENU] = array(
    'title' => 'Snippets: Manage',
    'description' => 'Edit and maintain the revisions of snippet.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('snippet_list_form'),
    'access arguments' => array('edit snippet content'),
    'file' => 'snippet.admin.inc',
  );
  
  $items[SNIPPETS_LIST_MENU . '/%snippet/edit'] = array(
    'title' => 'Edit Snippets',
    'description' => 'Edit snippet.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('snippet_form', 3),
    'access arguments' => array('edit snippet content'),
    'file' => 'snippet.admin.inc',
  );
  
  $items[SNIPPETS_LIST_MENU . '/%snippet/revisions'] = array(
    'title' => 'Revisions',
    'page callback' => 'snippet_revision_overview',
    'page arguments' => array(3),
    'access arguments' => array('edit snippet content'),
    'file' => 'snippet.admin.inc',
  );
  
  $items[SNIPPETS_LIST_MENU . '/%snippet/revisions/%/view'] = array(
    'title' => 'Revisions',
    'load arguments' => array(5),
    'page callback' => 'snippet_revision_view',
    'page arguments' => array(3),
    'access arguments' => array('edit snippet content'),
    'file' => 'snippet.admin.inc',
  );
  
  $items[SNIPPETS_LIST_MENU . '/%snippet/revisions/%/revert'] = array(
    'title' => 'Revisions',
    'load arguments' => array(5),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('snippet_revision_revert_confirm', 3),
    'access arguments' => array('edit snippet content'),
    'file' => 'snippet.admin.inc',
  );
  
  return $items;
}

/**
 * Implemetation of hook_permission()
 */
function snippet_permission() {
  $permissions = array();
  $permissions['administer snippet'] = array(
      'title' => t('Administer snippet'), 
      'description' => t('Perform administration tasks for snippet.'),
      'restrict access' => TRUE,
  );
  
  $permissions['access snippet list'] = array(
      'title' => t('Manage snippet'), 
      'description' => t('Perform managing tasks for snippet.'),
  );
  
  $permissions['edit snippet content'] = array(
      'title' => t('Edit snippet'), 
      'description' => t('Perform editing tasks for snippet content.'),
  );
  
  return $permissions;
}

/**
 * Loads the data for the snippet
 * @param $snippet_name
 *  machine understanable name of the snippet which wants to get loaded
 */
function snippet_load($snippet_name, $rid = NULL) {
  if ( $snippet_name) {
    ctools_include('export');
    $snippet = ctools_export_crud_load('snippet', $snippet_name);
    
    $snippet_revision = db_select('snippet_revision', 'sr')
                        ->fields('sr', array())
                        ->condition('name', $snippet->name);
    
    if ($rid) {
      $snippet_revision = $snippet_revision->condition('rid', $rid);
    }
    else {
      $snippet_revision = $snippet_revision->condition('is_current', 1);
    }
    $snippet_revision = $snippet_revision->execute()->fetch();
    $snippet->content = !empty($snippet_revision->content) ? $snippet_revision->content : '' ;
    $snippet->content_format = !empty($snippet_revision->content_format) ? $snippet_revision->content_format : NULL ;
    $snippet->timestamp = !empty($snippet_revision->timestamp) ? $snippet_revision->timestamp : NULL ;
    $snippet->is_current = !empty($snippet_revision->is_current) ? $snippet_revision->is_current : NULL ;
    $snippet->rid = !empty($snippet_revision->rid) ? $snippet_revision->rid : NULL ;
    return $snippet;
  }
}

/**
 * Implemetation of hook_theme()
 */
function snippet_theme() {
  return array(
    'snippet_content_show' => array(
      'variables' => array(),
    ),
  );
}

/**
 * Theme function to output the snippet
 * this helps render content for preview as well on live page
 */
function theme_snippet_content_show($vars) {

  // for viewing the preview of the snippet
  $in_preview = isset($vars['in_preview']) ? $vars['in_preview'] : 0;
  
  $snippet_contextual_links = $heighlight = $heighlight_style = $edit = $preview_heading = "";
  if (user_access('edit snippet content') && (!$in_preview)) {
    $heighlight = "snippet-highlight";
    $heighlight_style = "style='background: #FFFFEA;'";

    // get the destination
    $destination = drupal_get_destination();
    
    $operations['links']['edit'] = array(
      'title' => t('Edit this'),
      'href' => SNIPPETS_LIST_MENU . "/" . $vars['name'] . "/edit",
      'query' => $destination,
    );
    $operations['links']['revert'] = array(
      'title' => t('Revisions'),
      'href' => SNIPPETS_LIST_MENU . "/" . $vars['name'] . "/revisions",
      'query' => $destination,
      );
    $operations['attributes'] = array('class' => array('links', 'inline'));
    $snippet_contextual_links = theme('links', $operations);
    $snippet_contextual_links = "<div class='snippet-links'>{$snippet_contextual_links}</div>";
  }
  
  $heighlight_style = $heighlight_style;
  if ($in_preview) {
    $heighlight_style = "style='background: #FFFFEA;'";
    $preview_heading = '<h3>' . t('Preview') . '</h3>';
  }
  
  // this snippet_id would be used for submitting/updating the correct snippet
  $snippet_id = $vars['name'] . (@$vars['rid']) ? ("-" . $vars['rid']) : '';
  $content = "<div class = 'edit " . $edit . "' id = 'snippet-" . $snippet_id . "'>" . $vars['content'] . "</div>";
  
  $title = "<h2 class = 'snippet-title'>" . $vars['title'] . "</h2>";
  
  $output = "<div class = \"snippet-view {$heighlight}\" {$heighlight_style}>" . $preview_heading . $title . $content . $snippet_contextual_links . "</div>";
  return $output;
}

